# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kvs_pb2 as kvs__pb2


class KeyValueStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/project.KeyValueStore/Get',
                request_serializer=kvs__pb2.KeyRequest.SerializeToString,
                response_deserializer=kvs__pb2.KeyValueVersionReply.FromString,
                )
        self.GetRange = channel.unary_stream(
                '/project.KeyValueStore/GetRange',
                request_serializer=kvs__pb2.KeyRange.SerializeToString,
                response_deserializer=kvs__pb2.KeyValueVersionReply.FromString,
                )
        self.GetAll = channel.stream_stream(
                '/project.KeyValueStore/GetAll',
                request_serializer=kvs__pb2.KeyRequest.SerializeToString,
                response_deserializer=kvs__pb2.KeyValueVersionReply.FromString,
                )
        self.Put = channel.unary_unary(
                '/project.KeyValueStore/Put',
                request_serializer=kvs__pb2.KeyValueRequest.SerializeToString,
                response_deserializer=kvs__pb2.PutReply.FromString,
                )
        self.PutAll = channel.stream_stream(
                '/project.KeyValueStore/PutAll',
                request_serializer=kvs__pb2.KeyValueRequest.SerializeToString,
                response_deserializer=kvs__pb2.PutReply.FromString,
                )
        self.Del = channel.unary_unary(
                '/project.KeyValueStore/Del',
                request_serializer=kvs__pb2.KeyRequest.SerializeToString,
                response_deserializer=kvs__pb2.KeyValueVersionReply.FromString,
                )
        self.DelRange = channel.unary_stream(
                '/project.KeyValueStore/DelRange',
                request_serializer=kvs__pb2.KeyRange.SerializeToString,
                response_deserializer=kvs__pb2.KeyValueVersionReply.FromString,
                )
        self.DelAll = channel.stream_stream(
                '/project.KeyValueStore/DelAll',
                request_serializer=kvs__pb2.KeyRequest.SerializeToString,
                response_deserializer=kvs__pb2.KeyValueVersionReply.FromString,
                )
        self.Trim = channel.unary_unary(
                '/project.KeyValueStore/Trim',
                request_serializer=kvs__pb2.KeyRequest.SerializeToString,
                response_deserializer=kvs__pb2.KeyValueVersionReply.FromString,
                )


class KeyValueStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutAll(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Del(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelAll(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=kvs__pb2.KeyRequest.FromString,
                    response_serializer=kvs__pb2.KeyValueVersionReply.SerializeToString,
            ),
            'GetRange': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRange,
                    request_deserializer=kvs__pb2.KeyRange.FromString,
                    response_serializer=kvs__pb2.KeyValueVersionReply.SerializeToString,
            ),
            'GetAll': grpc.stream_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=kvs__pb2.KeyRequest.FromString,
                    response_serializer=kvs__pb2.KeyValueVersionReply.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=kvs__pb2.KeyValueRequest.FromString,
                    response_serializer=kvs__pb2.PutReply.SerializeToString,
            ),
            'PutAll': grpc.stream_stream_rpc_method_handler(
                    servicer.PutAll,
                    request_deserializer=kvs__pb2.KeyValueRequest.FromString,
                    response_serializer=kvs__pb2.PutReply.SerializeToString,
            ),
            'Del': grpc.unary_unary_rpc_method_handler(
                    servicer.Del,
                    request_deserializer=kvs__pb2.KeyRequest.FromString,
                    response_serializer=kvs__pb2.KeyValueVersionReply.SerializeToString,
            ),
            'DelRange': grpc.unary_stream_rpc_method_handler(
                    servicer.DelRange,
                    request_deserializer=kvs__pb2.KeyRange.FromString,
                    response_serializer=kvs__pb2.KeyValueVersionReply.SerializeToString,
            ),
            'DelAll': grpc.stream_stream_rpc_method_handler(
                    servicer.DelAll,
                    request_deserializer=kvs__pb2.KeyRequest.FromString,
                    response_serializer=kvs__pb2.KeyValueVersionReply.SerializeToString,
            ),
            'Trim': grpc.unary_unary_rpc_method_handler(
                    servicer.Trim,
                    request_deserializer=kvs__pb2.KeyRequest.FromString,
                    response_serializer=kvs__pb2.KeyValueVersionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project.KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/project.KeyValueStore/Get',
            kvs__pb2.KeyRequest.SerializeToString,
            kvs__pb2.KeyValueVersionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/project.KeyValueStore/GetRange',
            kvs__pb2.KeyRange.SerializeToString,
            kvs__pb2.KeyValueVersionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/project.KeyValueStore/GetAll',
            kvs__pb2.KeyRequest.SerializeToString,
            kvs__pb2.KeyValueVersionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/project.KeyValueStore/Put',
            kvs__pb2.KeyValueRequest.SerializeToString,
            kvs__pb2.PutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutAll(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/project.KeyValueStore/PutAll',
            kvs__pb2.KeyValueRequest.SerializeToString,
            kvs__pb2.PutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Del(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/project.KeyValueStore/Del',
            kvs__pb2.KeyRequest.SerializeToString,
            kvs__pb2.KeyValueVersionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/project.KeyValueStore/DelRange',
            kvs__pb2.KeyRange.SerializeToString,
            kvs__pb2.KeyValueVersionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelAll(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/project.KeyValueStore/DelAll',
            kvs__pb2.KeyRequest.SerializeToString,
            kvs__pb2.KeyValueVersionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/project.KeyValueStore/Trim',
            kvs__pb2.KeyRequest.SerializeToString,
            kvs__pb2.KeyValueVersionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
