# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kvs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tkvs.proto\x12\x07project\"3\n\nKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x03ver\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x06\n\x04_ver\"L\n\x08KeyRange\x12\x1f\n\x02\x66r\x18\x01 \x01(\x0b\x32\x13.project.KeyRequest\x12\x1f\n\x02to\x18\x02 \x01(\x0b\x32\x13.project.KeyRequest\"+\n\x0fKeyValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"=\n\x14KeyValueVersionReply\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\x12\x0b\n\x03ver\x18\x03 \x01(\x03\"F\n\x08PutReply\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07old_val\x18\x02 \x01(\t\x12\x0f\n\x07old_ver\x18\x03 \x01(\x03\x12\x0b\n\x03ver\x18\x04 \x01(\x03\x32\xc6\x04\n\rKeyValueStore\x12;\n\x03Get\x12\x13.project.KeyRequest\x1a\x1d.project.KeyValueVersionReply\"\x00\x12@\n\x08GetRange\x12\x11.project.KeyRange\x1a\x1d.project.KeyValueVersionReply\"\x00\x30\x01\x12\x42\n\x06GetAll\x12\x13.project.KeyRequest\x1a\x1d.project.KeyValueVersionReply\"\x00(\x01\x30\x01\x12\x34\n\x03Put\x12\x18.project.KeyValueRequest\x1a\x11.project.PutReply\"\x00\x12;\n\x06PutAll\x12\x18.project.KeyValueRequest\x1a\x11.project.PutReply\"\x00(\x01\x30\x01\x12;\n\x03\x44\x65l\x12\x13.project.KeyRequest\x1a\x1d.project.KeyValueVersionReply\"\x00\x12@\n\x08\x44\x65lRange\x12\x11.project.KeyRange\x1a\x1d.project.KeyValueVersionReply\"\x00\x30\x01\x12\x42\n\x06\x44\x65lAll\x12\x13.project.KeyRequest\x1a\x1d.project.KeyValueVersionReply\"\x00(\x01\x30\x01\x12<\n\x04Trim\x12\x13.project.KeyRequest\x1a\x1d.project.KeyValueVersionReply\"\x00\x42\x1f\n\x1b\x62r.ufu.facom.gbc074.projectP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033br.ufu.facom.gbc074.projectP\001'
  _globals['_KEYREQUEST']._serialized_start=22
  _globals['_KEYREQUEST']._serialized_end=73
  _globals['_KEYRANGE']._serialized_start=75
  _globals['_KEYRANGE']._serialized_end=151
  _globals['_KEYVALUEREQUEST']._serialized_start=153
  _globals['_KEYVALUEREQUEST']._serialized_end=196
  _globals['_KEYVALUEVERSIONREPLY']._serialized_start=198
  _globals['_KEYVALUEVERSIONREPLY']._serialized_end=259
  _globals['_PUTREPLY']._serialized_start=261
  _globals['_PUTREPLY']._serialized_end=331
  _globals['_KEYVALUESTORE']._serialized_start=334
  _globals['_KEYVALUESTORE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
